name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update README.md
      run: make -B README.md

    - name: Git Commit/Push Changes
      uses: actions-x/commit@v6
      with:
        message: "Auto generating README.md"
        files: README.md
